InvestigacionCRUD/Models/Classes.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace InvestigacionCRUD.Models
{
    /// <summary>
    /// Modelo de datos para un usuario.
    /// </summary>
    public class User
    {
        public long? Id { get; set; } // Identificador único del usuario
        public string? Name { get; set; } // Nombre del usuario
        public string? Cedula { get; set; } // Cédula del usuario
        public int Age { get; set; } // Edad del usuario
        public string? Email { get; set; } // Correo electrónico del usuario
        public List<Task>? Tasks { get; set; } // Lista de tareas asignadas al usuario
    }

    /// <summary>
    /// Modelo de datos para una tarea.
    /// </summary>
    public class Task
    {
        public int Id { get; set; } // Identificador único de la tarea

        [Required(ErrorMessage = "El título es requerido")]
        public string? Title { get; set; } // Título de la tarea

        [Required(ErrorMessage = "La descripción es requerida")]
        public string? Description { get; set; } // Descripción de la tarea

        [Required(ErrorMessage = "La fecha de vencimiento es requerida")]
        public DateTime? DueDate { get; set; } // Fecha de vencimiento de la tarea

        [Required(ErrorMessage = "Las horas son requeridas")]
        public int Hours { get; set; } // Horas requeridas para completar la tarea

        [Required(ErrorMessage = "La ubicación es requerida")]
        public string? Location { get; set; } // Ubicación de la tarea

        [Required(ErrorMessage = "La prioridad es requerida")]
        public string? Priority { get; set; } // Prioridad de la tarea

        [Required(ErrorMessage = "El estado de la tarea es requerido")]
        public string? TaskProgress { get; set; } // Estado actual de la tarea

        public string? PhotoUrl { get; set; } // URL de la foto asociada a la tarea

        [Required(ErrorMessage = "El usuario asignado es requerido")]
        public int UserId { get; set; } // Identificador del usuario asignado a la tarea

        public bool IsReady { get; set; } = false; // Indica si la tarea está completada

        public User User { get; set; } // Usuario asignado a la tarea
    }
}

InvestigacionCRUD/Models/ErrorViewModel.cs
namespace InvestigacionCRUD.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

InvestigacionCRUD/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using InvestigacionCRUD.Models;

namespace InvestigacionCRUD.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

InvestigacionCRUD/Controllers/TaskController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;
using InvestigacionCRUD.Models;

namespace InvestigacionCRUD.Controllers
{
    /// <summary>
    /// Controlador para gestionar las operaciones relacionadas con las tareas.
    /// </summary>
    public class TaskController : Controller
    {
        private readonly IHttpClientFactory _clientFactory;
        private readonly string _baseUrl = "http://localhost:8080";

        public TaskController(IHttpClientFactory clientFactory)
        {
            _clientFactory = clientFactory;
        }

        // Método genérico para obtener la respuesta de la API de forma asíncrona
        private async Task<T> GetApiResponseAsync<T>(string relativeUrl)
        {
            using var client = _clientFactory.CreateClient();
            var response = await client.GetAsync(_baseUrl + relativeUrl);

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                return JsonSerializer.Deserialize<T>(content, new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                });
            }

            throw new HttpRequestException($"Error: {response.StatusCode}");
        }

        // Vista para mostrar la lista de tareas
        public async Task<IActionResult> TaskIndex()
        {
            try
            {
                var users = await GetApiResponseAsync<List<User>>("/user/list");
                return View(users);
            }
            catch (HttpRequestException ex)
            {
                ViewBag.Message = ex.Message;
                return View(new List<User>());
            }
        }

        // Vista para agregar una nueva tarea
        public async Task<IActionResult> TaskAdd()
        {
            var users = await GetApiResponseAsync<List<User>>("/user/list");
            ViewBag.Users = users;
            return View();
        }

        // Método para agregar una nueva tarea
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> TaskAdd(int userId, InvestigacionCRUD.Models.Task task)
        {
            var url = $"/task/create/{userId}";
            using var client = _clientFactory.CreateClient();
            var response = await client.PostAsJsonAsync(_baseUrl + url, task);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction(nameof(TaskIndex));
            }

            throw new HttpRequestException($"Error: {response.StatusCode}");
        }

        // Método para eliminar una tarea
[HttpDelete]
public async Task<IActionResult> DeleteTask(int id)
{
    var url = $"/task/delete/{id}";
    using var client = _clientFactory.CreateClient();
    var response = await client.DeleteAsync(_baseUrl + url);

    if (response.IsSuccessStatusCode)
    {
        return Ok(new { success = true });
    }

    return StatusCode((int)response.StatusCode, new { success = false, message = response.ReasonPhrase });
}



        // Vista para mostrar los detalles de una tarea
        public async Task<IActionResult> GetById(int id)
        {
            var relativeUrl = $"/task/{id}";
            var task = await GetApiResponseAsync<InvestigacionCRUD.Models.Task>(relativeUrl);

            if (task != null)
            {
                return View(task);
            }
            else
            {
                return NotFound();
            }
        }

        // Método para actualizar una tarea
        [HttpPatch]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> TaskUpdate(int id, InvestigacionCRUD.Models.Task taskDetails)
        {
            var url = $"/task/update/{id}";
            using var client = _clientFactory.CreateClient();
            var response = await client.PatchAsJsonAsync(_baseUrl + url, taskDetails);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction(nameof(TaskIndex));
            }

            throw new HttpRequestException($"Error: {response.StatusCode}");
        }
    }
}

InvestigacionCRUD/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;
using InvestigacionCRUD.Models;

namespace InvestigacionCRUD.Controllers
{
    /// <summary>
    /// Controlador para gestionar las operaciones relacionadas con los usuarios.
    /// </summary>
    public class UserController : Controller
    {
        private readonly IHttpClientFactory _clientFactory;
        private readonly string _baseUrl = "http://localhost:8080";

        public UserController(IHttpClientFactory clientFactory)
        {
            _clientFactory = clientFactory;
        }

        // Método genérico para obtener la respuesta de la API de forma asíncrona
        private async Task<T> GetApiResponseAsync<T>(string relativeUrl)
        {
            using var client = _clientFactory.CreateClient();
            var response = await client.GetAsync(_baseUrl + relativeUrl);

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                return JsonSerializer.Deserialize<T>(content, new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                });
            }

            throw new HttpRequestException($"Error: {response.StatusCode}");
        }

        // Vista para mostrar la lista de usuarios
        public async Task<IActionResult> Index()
        {
            try
            {
                var users = await GetApiResponseAsync<List<User>>("/user/list");
                return View(users);
            }
            catch (HttpRequestException ex)
            {
                ViewBag.Message = ex.Message;
                return View(new List<User>());
            }
        }
    }
}

InvestigacionCRUD/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h2>Bienvenido Tareas Pochas</h2>
<p>
    Utilice el menú de navegación para gestionar usuarios.
</p>

InvestigacionCRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InvestigacionCRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InvestigacionCRUD.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InvestigacionCRUD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "User")">Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("TaskIndex", "Task")">Tareas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("TaskAdd", "Task")">Añadir Tarea</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - InvestigacionCRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

InvestigacionCRUD/Views/task/TaskAdd.cshtml
@model InvestigacionCRUD.Models.Task
@{
    ViewBag.Title = "Añadir Tarea";
    var users = ViewBag.Users as List<InvestigacionCRUD.Models.User>;
}

<!-- Encabezado -->
<h2>Añadir Tarea</h2>

<!-- Formulario para añadir una tarea -->
<form asp-action="TaskAdd" method="post" enctype="multipart/form-data">
    <!-- Título -->
    <div class="form-group">
        <label asp-for="Title" class="control-label">Título</label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <!-- Descripción -->
    <div class="form-group">
        <label asp-for="Description" class="control-label">Descripción</label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <!-- Fecha de vencimiento -->
    <div class="form-group">
        <label asp-for="DueDate" class="control-label">Fecha de vencimiento</label>
        <input asp-for="DueDate" type="date" class="form-control" />
        <span asp-validation-for="DueDate" class="text-danger"></span>
    </div>
    <!-- Horas requeridas -->
    <div class="form-group">
        <label asp-for="Hours" class="control-label">Horas requeridas</label>
        <input asp-for="Hours" type="number" class="form-control" />
        <span asp-validation-for="Hours" class="text-danger"></span>
    </div>
    <!-- Ubicación -->
    <div class="form-group">
        <label asp-for="Location" class="control-label">Ubicacion</label>
        <input asp-for="Location" class="form-control" />
        <span asp-validation-for="Location" class="text-danger"></span>
    </div>
    <!-- Prioridad -->
    <div class="form-group">
        <label asp-for="Priority" class="control-label">Prioridad</label>
        <select asp-for="Priority" class="form-control">
            <option value="LOW">LOW</option>
            <option value="MID">MID</option>
            <option value="HIGH">HIGH</option>
        </select>
        <span asp-validation-for="Priority" class="text-danger"></span>
    </div>
    <!-- Estado de la tarea -->
    <div class="form-group">
        <label asp-for="TaskProgress" class="control-label">Estado</label>
        <select asp-for="TaskProgress" class="form-control">
            <option value="PENDING">PENDING</option>
            <option value="IN_PROGRESS">IN PROGRESS</option>
            <option value="DONE">DONE</option>
        </select>
        <span asp-validation-for="TaskProgress" class="text-danger"></span>
    </div>
    <!-- Imagen -->
    <div class="form-group">
        <label asp-for="PhotoUrl" class="control-label">Imagen</label>
        <input type="file" id="imageFile" class="form-control" onchange="uploadImage()" />
        <input type="hidden" id="photoUrl" name="PhotoUrl" />
        <div id="imagePreview"></div>
        <span asp-validation-for="PhotoUrl" class="text-danger"></span>
    </div>
    <!-- Usuario asignado -->
    <div class="form-group">
        <label asp-for="UserId" class="control-label">Usuario</label>
        <select asp-for="UserId" class="form-control">
            @if (users != null)
            {
                @foreach (var user in users)
                {
                    <option value="@user.Id">@user.Name</option>
                }
            }
        </select>
        <span asp-validation-for="UserId" class="text-danger"></span>
    </div>
    <!-- Botón para enviar el formulario -->
    <div class="form-group">
        <input type="submit" value="Añadir" class="btn btn-primary" />
    </div>
</form>

<!-- Enlace para volver a la lista de tareas -->
<div>
    <a asp-action="TaskIndex">Volver a la lista</a>
</div>

<!-- Scripts -->
@section Scripts {
    <script>
        // Función para subir la imagen al servidor
        function uploadImage() {
            var fileInput = document.getElementById('imageFile');
            var formData = new FormData();
            formData.append('file', fileInput.files[0]);

            fetch('http://localhost:8080/api/images/upload', {
                method: 'POST',
                body: formData
            })
            .then(response => response.text())
            .then(url => {
                document.getElementById('photoUrl').value = url;
                document.getElementById('imagePreview').innerHTML = '<img src="' + url + '" class="img-thumbnail" style="max-width: 200px;" />';
            })
            .catch(error => console.error('Error:', error));
        }
    </script>
    <partial name="_ValidationScriptsPartial" />
}

InvestigacionCRUD/Views/task/TaskIndex.cshtml
@using InvestigacionCRUD.Controllers; 
@model List<InvestigacionCRUD.Models.User>

@{
    ViewBag.Title = "Lista de Tareas";
}

<!-- Incluir CSS de Bootstrap -->
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

<!-- Incluir JS de Bootstrap (jQuery requerido) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<h2>Lista de Tareas</h2>

<!-- Tabla para mostrar las tareas -->
<table class="table">
    <thead>
        <tr>
            <th>Nombre del Usuario</th>
            <th>Título de la Tarea</th>
            <th>Fecha de Vencimiento</th>
            <th>Horas Requeridas</th>
            <th>Prioridad</th>
            <th>Estado</th>
            <th>Detalles</th>
        </tr>
    </thead>
    <tbody>
        <!-- Iterar sobre cada usuario y sus tareas -->
        @foreach (var user in Model)
        {
            @foreach (var task in user.Tasks)
            {
                <tr>
                    <!-- Mostrar el nombre del usuario y la foto de la tarea -->
                    <td>
                        <img src="http://localhost:8080/@task.PhotoUrl" class="rounded-circle" alt="Foto de @user.Name" style="width: 40px; height: 40px; margin-right: 10px;">
                        @user.Name
                    </td>
                    <!-- Mostrar el título, fecha de vencimiento, horas requeridas, prioridad, estado y botón de detalles de la tarea -->
                    <td>@task.Title</td>
                    <td>@task.DueDate?.ToString("dd-MM-yyyy")</td>
                    <td>@task.Hours horas</td>
                    <td>
                        <!-- Aplicar clase de Bootstrap según la prioridad -->
                        <span class="badge @GetPriorityClass(task.Priority)">@task.Priority</span>
                    </td>
                    <td>
                        <!-- Aplicar clase de Bootstrap según el progreso de la tarea -->
                        <span class="badge @GetTaskProgressClass(task.TaskProgress)">@task.TaskProgress</span>
                    </td>
                    <td>
                        <!-- Botón para mostrar el modal de detalles de la tarea -->
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#taskModal_@task.Id">
                            Ver Detalles
                        </button>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<!-- Funciones en C# para asignar clases CSS según la prioridad y el progreso de la tarea -->
@functions {
    public string GetPriorityClass(string priority)
    {
        return priority switch
        {
            "LOW" => "badge-success",
            "MID" => "badge-warning",
            "HIGH" => "badge-danger",
            _ => ""
        };
    }

    public string GetTaskProgressClass(string taskProgress)
    {
        return taskProgress switch
        {
            "PENDING" => "badge-secondary",
            "IN_PROGRESS" => "badge-info",
            "DONE" => "badge-danger",
            _ => ""
        };
    }
}

<!-- Modales para mostrar detalles y modificar el estado de las tareas -->
@foreach (var user in Model)
{
    @foreach (var task in user.Tasks)
    {
        <!-- Modal para mostrar detalles de la tarea -->
        <div class="modal fade" id="taskModal_@task.Id" tabindex="-1" role="dialog" aria-labelledby="taskModalLabel_@task.Id" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="taskModalLabel_@task.Id">Detalles de la Tarea</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <!-- Mostrar detalles de la tarea -->
                        <div class="row">
                            <div class="col-md-4">
                                <img src="http://localhost:8080/@task.PhotoUrl" class="img-fluid" alt="Imagen de la Tarea">
                            </div>
                            <div class="col-md-8">
                                <p><strong>Título:</strong> @task.Title</p>
                                <p><strong>Descripción:</strong> @task.Description</p>
                                <p><strong>Fecha de Vencimiento:</strong> @task.DueDate?.ToString("dd-MM-yyyy")</p>
                                <p><strong>Horas Requeridas:</strong> @task.Hours horas</p>
                                <p><strong>Ubicación:</strong> @task.Location</p>
                                <p><strong>Prioridad:</strong> @task.Priority</p>
                                <p><strong>Estado:</strong> @task.TaskProgress</p>
                                
                                <!-- Opciones de Actualizar y Eliminar -->
                                <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#editTaskStatusModal_@task.Id">
                                    Actualizar
                                </button>
                                <button class="btn btn-danger" onclick="deletionTask(@task.Id, '@task.Title')">Eliminar HTTP</button>
                                <button class="btn btn-danger" onclick="deleteTask(@task.Id, '@task.Title')">Eliminar</button>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    </div>
                </div>
            </div>
        </div>
    }

    @foreach (var task in user.Tasks)
    {
        <!-- Modal para modificar el estado de la tarea -->
        <div class="modal fade" id="editTaskStatusModal_@task.Id" tabindex="-1" role="dialog" aria-labelledby="editTaskStatusModalLabel_@task.Id" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="editTaskStatusModalLabel_@task.Id">Modificar Estado de la Tarea</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <!-- Formulario para modificar el estado de la tarea -->
                        <form id="editTaskStatusForm_@task.Id">
                            <div class="form-group">
                                <label for="TaskProgress_@task.Id">Estado</label>
                                <select id="TaskProgress_@task.Id" class="form-control">
                                    <option value="PENDING">Pendiente</option>
                                    <option value="IN_PROGRESS">En Progreso</option>
                                    <option value="DONE">Completada</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="IsReady_@task.Id">¿Está Listo?</label>
                                <input type="checkbox" id="IsReady_@task.Id" class="form-check-input">
                            </div>

                            <!-- Botón para guardar los cambios -->
                            <button type="button" class="btn btn-primary" onclick="updateTaskStatus(@task.Id)">Guardar Cambios</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    }
}


<!-- Token de Verificación -->
@Html.AntiForgeryToken()

<script type="text/javascript">
    function deletionTask(taskId, taskTitle) {
        if (confirm("¿Estás seguro de que deseas eliminar la tarea '" + taskTitle + "'?")) {
            $.ajax({
                url: '@Url.Action("DeleteTask", "Task")/' + taskId,
                type: 'DELETE',
                headers: {
                    'RequestVerificationToken': $('input[name="__RequestVerificationToken"]').val()
                },
                success: function(result) {
                    if (result.success) {
                        location.reload();
                    } else {
                        alert('Error al eliminar la tarea: ' + result.message);
                    }
                },
                error: function(xhr, status, error) {
                    alert('Error al eliminar la tarea: ' + error);
                }
            });
        }
    }
</script>

<!-- Funciones JavaScript para eliminar una tarea y actualizar el estado de una tarea -->
<script>
    async function deleteTask(taskId, taskTitle) {
        if (confirm(`¿Estás seguro de que quieres eliminar la tarea ${taskTitle}?`)) {
            try {
                const response = await fetch(`http://localhost:8080/task/delete/${taskId}`, {
                    method: 'DELETE'
                });

                if (response.ok) {
                    // Redirige a la página de listado de tareas o actualiza la vista según sea necesario
                    window.location.href = '/Task/TaskIndex';
                } else {
                    throw new Error('Error al eliminar la tarea');
                }
            } catch (error) {
                console.error(error);
                alert('Hubo un problema al eliminar la tarea.');
            }
        }
    }

    async function updateTaskStatus(taskId) {
        const taskProgress = document.getElementById(`TaskProgress_${taskId}`).value;
        const isReady = document.getElementById(`IsReady_${taskId}`).checked;
        const url = `http://localhost:8080/task/update/${taskId}`;

        const data = {
            taskProgress: taskProgress,
            isReady: isReady
        };

        try {
            const response = await fetch(url, {
                method: 'PATCH',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(data)
            });

            if (response.ok) {
                // Actualiza la vista o redirige a la lista de tareas
                window.location.href = '/Task/TaskIndex';
            } else {
                throw new Error('Error al actualizar el estado de la tarea');
            }
        } catch (error) {
            console.error(error);
            alert('Hubo un problema al actualizar el estado de la tarea.');
        }
    }
</script>

InvestigacionCRUD/Views/user/index.cshtml
@model List<InvestigacionCRUD.Models.User>

@{
    ViewBag.Title = "Lista de Usuarios";
}

<h2>Lista de Usuarios</h2>

@if (Model != null)
{
    <ul>
        @foreach (var user in Model)
        {
            <li>
                <strong>Nombre:</strong> @user.Name <br>
                <strong>Cédula:</strong> @user.Cedula<br>
                <strong>Edad:</strong> @user.Age<br>
                <strong>Email:</strong> @user.Email <br>
                <strong>Tareas:</strong>
                <ul>
                    @if (user.Tasks != null)
                    {
                        @foreach (var task in user.Tasks)
                        {
                            <li>
                                @task.Description - @(task.IsReady ? "Completado" : "Pendiente")
                            </li>

                        }
                    }
                    else
                    {
                        <li>No hay tareas</li>
                    }
                </ul>
             
            </li>
        }
    </ul>
}
else
{
    <p>@ViewBag.Message</p>
}